apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: default
  name: deploy-reader
rules:
- apiGroups: ["apps"] # "" indicates the core API grouop
  resources: ["pods","deployments"]
  verbs: ["get", "watch", "list"] 
