apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-deploys
  namespace: default
subjects:
- kind: User
  name: anna
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deploy-reader
  apiGroup: rbac.authorization.k8s.io

